仕様変更点を修正しました
GTM106/BalloonGame pull request #54
Opened 2023-10-15 04:41 UTC by yuto-0122

2023-10-15 04:42 UTC, yuto-0122 commented
修正しました。
確認お願いします。

2023-10-15 04:52 UTC, GTM106 requested changes
修正してほしい点を2点あげました。確認して修正をお願いします。

2023-10-15 04:52 UTC, GTM106 commented on BalloonGame/Assets/Scripts/Player/BalloonController.cs
> +    Gimmick,
Gimmickはどのギミックが判断できないので、判断できる名前に変更してください。

2023-10-15 04:52 UTC, GTM106 commented on BalloonGame/Assets/Scripts/Player/BalloonController.cs
> +        _airEvent.OnExitAirVent += OnExitAirVent;
`_airEvent.OnEnterAirVent += OnEnterAirVent;`
イベントを購読したら解除する必要があります。
OnDestroyに ` _airEvent.OnEnterAirVent -= OnEnterAirVent;` のように追加してください。

2023-10-15 04:52 UTC, GTM106 commented on BalloonGame/Assets/Atii/MAT/MAT_AtiiBalloon.mat
この変更点は消していただけると助かります

2023-10-15 05:22 UTC, GTM106 approved these changes
コードの問題点はなさそうです。機能に問題がなければマージをお願いします。

2023-10-16 10:09 UTC, merged

2023-10-16 10:09 UTC, Harmony82 commented
修正を確認しました。マージします。