レビュー前でRevertしたものを再度マージするためのPL
GTM106/BalloonGame pull request #71
Opened 2023-10-27 10:58 UTC by megutan30

2023-10-27 15:09 UTC, GTM106 requested changes
コーディング面はよく書けていると思います。命名もわかりやすく読みやすいコードでした。
コスト面への対応ができていないので各レビューコメントを読んで修正してください。

レビューでも変更方法でも何でも良いので、分からなければ遠慮せず質問してください。

2023-10-27 15:09 UTC, GTM106 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/CameraPositionNotifier.cs
> +    public event CameraPositionChangedEventHandler CameraPositionChanged;
イベントの引数を(object sender, CameraPositionChangedEventArgs e)としていますが、senderを渡す意図はなんですか？
渡す必要があるなら、objectではなく自クラス(CameraPositionNotifier)で良いのではないでしょうか。

CameraPositionChangedEventArgsは参考になりました。イベント駆動プログラミングの一貫性が出るため良い試みだと思います。

2023-10-27 17:53 UTC, megutan30 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/SwitchSurfaceTypeEditor.cs
> +}
了解です。知りませんでした。ありがとうございます。

2023-10-27 17:53 UTC, megutan30 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/SwitchSurfaceType.cs
> +using UnityEditor;
了解です。

2023-10-27 17:53 UTC, megutan30 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/SwitchSurfaceType.cs
> +        }
好みの問題なので、可読性に差異がないならこちらにします。

2023-10-27 17:54 UTC, megutan30 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/SwitchSurfaceType.cs
> +        Collider col = GetComponent<Collider>();
無いですね。修正します。

2023-10-27 17:54 UTC, megutan30 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/SwitchSurfaceType.cs
> +        }
これに関しては、スクリプトの関係上水のプレファブのない今の状態なら水の個数分アタッチする必要があるので、アタッチする手間よりかはコストが多少重くなってもよいと思ってこうしました。いずれは水もプレファブとして扱うと思うので直しておきます。また、他のオブジェクトが参照される可能性も考えて、シングルトンパターンを用いたりして共有できるようにした方がよかったりしますか？

2023-10-27 17:55 UTC, megutan30 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/CameraPositionNotifier.cs
> +    public event CameraPositionChangedEventHandler CameraPositionChanged;
それもそうですね。

2023-10-27 17:55 UTC, megutan30 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/CameraPositionNotifier.cs
> +        Vector3 currentCameraPosition = Camera.main.transform.position;
知りませんでした。直しておきます。

2023-10-27 17:55 UTC, megutan30 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/CameraPositionNotifier.cs
> +        }
勉強になります。

2023-10-27 17:55 UTC, megutan30 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/CameraPositionNotifier.cs
> +    public event CameraPositionChangedEventHandler CameraPositionChanged;
イベントハンドラがどのオブジェクトからイベントが発生したかを特定するのに便利なので、そっちのほうが柔軟性があっていいかなと考えたからですね。依存しなくていいので。型安全性やデバッグなどのことを考えたら自クラスを渡した方が確かにいいですね。
何方にするかは設計等による気もしますがどうしますか？

2023-10-28 00:23 UTC, GTM106 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/SwitchSurfaceType.cs
> +        }
水のプレハブがないのは盲点でした。私がこのプルリク外で別途修正しますね。
また、都度アタッチする手間に関してですが[Reset()](https://docs.unity3d.com/ja/2021.1/ScriptReference/MonoBehaviour.Reset.html)というUnityのメソッドを用いることで解決可能です。

ほかのオブジェクトが参照される可能性というのがよく分かっていませんが、シングルトンにする必要は無いと思います。(ただ、シングルトンすることでアタッチし忘れみたいなミスは減りますが...正直悩ましいところです)

2023-10-28 00:53 UTC, GTM106 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/CameraPositionNotifier.cs
> +    public event CameraPositionChangedEventHandler CameraPositionChanged;
> イベントハンドラがどのオブジェクトからイベントが発生したかを特定するのに便利なので、そっちのほうが柔軟性があっていいかなと考えたからですね。依存しなくていいので。型安全性やデバッグなどのことを考えたら自クラスを渡した方が確かにいいですね。

意図があるなら自クラスに変えてsenderを渡す状態で構いません。ただ、使用者が困ることが推測されるのでコメントを残してあげると丁寧かと思います。

> 何方にするかは設計等による気もしますがどうしますか？

こういったコードは書いていませんでした(というかその手があったかといったところです)。
上記にもある通り、objectから自クラスに変えてsenderを渡す形にしましょう。そして、senderの意図が伝わりにくいため、適切にわかりやすいコメントを残す形でお願いします。

2023-10-28 05:11 UTC, GTM106 requested changes
2点気になる点を記述しました。よろしくお願いします。

2023-10-28 05:11 UTC, GTM106 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/SwitchSurfaceType.cs
> +    private Collider cachedCollider; // �R���C�_�[�R���|�[�l���g�̃L���b�V��
この`Renderer objectRenderer;`と`Collider cachedCollider;`の2つは[SerializeField]をつけることはできませんか？

2023-10-28 05:11 UTC, GTM106 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/SwitchSurfaceType.cs
> +    private Collider cachedCollider; // �R���C�_�[�R���|�[�l���g�̃L���b�V��
[SerializeField]属性に関する全体的な話ですが、[Required]属性もつけることでインスペクタにてnullだった場合警告が出るようになっています。そうするとアタッチミスがどこなのかとかがすぐにわかるようになっています。
(これはエディタ拡張で行っているものなため、一般的なプロジェクトではできません)
```csharp
//使用例
[SerializeField, Required] CameraPositionNotifier cameraPositionNotifier;
```

2023-10-28 11:56 UTC, GTM106 requested changes
レビューコメントを見て再度修正をお願いします。

2023-10-28 11:56 UTC, GTM106 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/SwitchSurfaceType.cs
> +    }
変更が中途半端なので再度変更してください。Colliderも[SerializeField]にできるはずです。
[SerializeField]属性をつけるなら18，19行目のGetComponentは不要です。

コードを書き終わったら整形を忘れずにするようにしましょう。
Visual Studioであれば、「Ctrl+K→Ctrl+D」でショートカット整形が可能です。

2023-10-28 12:38 UTC, megutan30 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/SwitchSurfaceType.cs
> +    }
修正しました。またReset関数追加したんですが、使い方的には問題ありませんか？

2023-10-28 14:05 UTC, GTM106 commented on BalloonGame/Assets/VFX/_Test/DynamicallySwitchMaterilSettings/SwitchSurfaceType.cs
> +    }
問題ないです！

2023-10-28 14:07 UTC, GTM106 approved these changes
指摘した部分の修正をすべて確認しました。
お疲れ様でした。

@yuto-0122 からレビューが来たらその時に再度対応お願いします。

2023-11-04 05:33 UTC, yuto-0122 approved these changes

2023-11-04 05:33 UTC, merged